services:
  - type: web
    name: signal-clone-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /live
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_BACKEND
        value: postgresql
      - key: DATABASE_URL
        fromDatabase:
          name: signal-clone-db
          property: connectionString
      - key: REDIS_BACKEND
        value: redis
      - key: REDIS_URL
        value: "" # Please manually link your Redis instance if using Render Redis or Upstash
      - key: BACKEND_CORS_ORIGINS
        sync: false

databases:
  - name: signal-clone-db
    databaseName: signal
    user: signal
    region: oregon
    plan: free
