# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default version is suitable
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# timezone =

# max length of characters to clone to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow scientists to define custom
# variable definitions inside alembic.ini or env.py
# custom_variable = value

# version path separator; default is os.pathsep.
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# set to 'true' to search source files recursively for migrations
# recursive_version_locations = false

# the database URL
sqlalchemy.url = sqlite:///./signal_clone.db

[post_write_hooks]
# post_write_hooks defines scripts or tools that run after a migration file is written.

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
