"""advanced_messaging_columns_and_models

Revision ID: 3d2dcb3f8b00
Revises: be1874be0702
Create Date: 2026-07-26 15:26:42.804185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2dcb3f8b00'
down_revision: Union[str, Sequence[str], None] = 'be1874be0702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_conv_drafts_conv_user')
    )
    op.create_index(op.f('ix_conversation_drafts_conversation_id'), 'conversation_drafts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_drafts_user_id'), 'conversation_drafts', ['user_id'], unique=False)
    op.create_table('messages_deleted_for_me',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_id', name='uq_msg_deleted_for_me_user_msg')
    )
    op.create_index(op.f('ix_messages_deleted_for_me_message_id'), 'messages_deleted_for_me', ['message_id'], unique=False)
    op.create_index(op.f('ix_messages_deleted_for_me_user_id'), 'messages_deleted_for_me', ['user_id'], unique=False)
    op.create_table('starred_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'message_id', name='uq_starred_messages_user_msg')
    )
    op.create_index(op.f('ix_starred_messages_message_id'), 'starred_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_starred_messages_user_id'), 'starred_messages', ['user_id'], unique=False)
    op.add_column('messages', sa.Column('client_message_id', sa.String(length=100), nullable=True))
    op.add_column('messages', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('is_draft', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('messages', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_messages_client_message_id'), 'messages', ['client_message_id'], unique=False)
    op.create_index(op.f('ix_messages_scheduled_at'), 'messages', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_scheduled_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_client_message_id'), table_name='messages')
    op.drop_column('messages', 'is_pinned')
    op.drop_column('messages', 'is_draft')
    op.drop_column('messages', 'scheduled_at')
    op.drop_column('messages', 'client_message_id')
    op.drop_index(op.f('ix_starred_messages_user_id'), table_name='starred_messages')
    op.drop_index(op.f('ix_starred_messages_message_id'), table_name='starred_messages')
    op.drop_table('starred_messages')
    op.drop_index(op.f('ix_messages_deleted_for_me_user_id'), table_name='messages_deleted_for_me')
    op.drop_index(op.f('ix_messages_deleted_for_me_message_id'), table_name='messages_deleted_for_me')
    op.drop_table('messages_deleted_for_me')
    op.drop_index(op.f('ix_conversation_drafts_user_id'), table_name='conversation_drafts')
    op.drop_index(op.f('ix_conversation_drafts_conversation_id'), table_name='conversation_drafts')
    op.drop_table('conversation_drafts')
    # ### end Alembic commands ###
